--------------------------------------------------------
-- 	CREATE TABLE STRUCTURE WITHOUT PK 
--------------------------------------------------------

CREATE TABLE "WEBSTORE"."T_GENERATOR" 
   (	
   "GEN_KEY" VARCHAR2(255 BYTE) NOT NULL,   
	"GEN_VALUE" NUMBER NOT NULL
   );
   

CREATE TABLE "WEBSTORE"."T_PRODUCT_TYPE" 
(
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2 (50 BYTE) NOT NULL
);

CREATE TABLE "WEBSTORE"."T_ORDER_TYPE" 
(
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2 (50 BYTE) NOT NULL
);

CREATE TABLE "WEBSTORE"."T_ROLE" 
(
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2 (50 BYTE) NOT NULL
);

CREATE TABLE "WEBSTORE"."T_USER" 
(
	"ID" NUMBER NOT NULL,
	"USERNAME" VARCHAR2 (30 BYTE) NOT NULL,
	"PASSWORD" VARCHAR2(50 BYTE) NOT NULL,
	"ROLE_ID" NUMBER NOT NULL
);

CREATE TABLE "WEBSTORE"."T_PRODUCT" 
(
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2 (50 BYTE) NOT NULL,
	"PRODUCT_TYPE_ID" NUMBER NOT NULL,
	"SINGLE_PRICE" NUMBER NOT NULL,
	"QUANTITY" NUMBER NOT NULL,
	"ACTIVE" NUMBER NOT NULL
);

CREATE TABLE "WEBSTORE"."T_CUSTOMER" 
(
	"ID" NUMBER NOT NULL,
	"NAME" VARCHAR2 (50 BYTE) NOT NULL,
	"BIRTH_DATE" DATE NOT NULL,
	"ADDRESS" VARCHAR2 (100 BYTE),
	"USER_ID" NUMBER NOT NULL,
	"ACTIVE" NUMBER NOT NULL
);

CREATE TABLE "WEBSTORE"."T_ORDER" 
(
	"ID" NUMBER NOT NULL,
	"CUSTOMER_ID" NUMBER NOT NULL,
	"ORDER_TYPE_ID" NUMBER NOT NULL,
	"TOTAL" NUMBER NOT NULL,
	"PURCHASE_DATE" DATE NOT NULL,
	"COMMENT" VARCHAR2 (200 BYTE)
);


CREATE TABLE "WEBSTORE"."T_ORDER_DETAILS" 
(
	"ID" NUMBER NOT NULL,
	"ORDER_ID" NUMBER NOT NULL,
	"PRODUCT_ID" NUMBER NOT NULL,
	"QUANTITY" NUMBER NOT NULL,
	"PRICE" NUMBER NOT NULL,
	"CURRENCY_ID" NUMBER NOT NULL,
);


--------------------------------------------------------
-- 	CREATE TABLE PRIMARY KEYS 
--------------------------------------------------------

ALTER TABLE "WEBSTORE"."T_USER" ADD CONSTRAINT "T_USER_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_ROLE" ADD CONSTRAINT "T_ROLE_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_PRODUCT" ADD CONSTRAINT "T_PRODUCT_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_PRODUCT_TYPE" ADD CONSTRAINT "T_PRODUCT_TYPE_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_CUSTOMER" ADD CONSTRAINT "T_CUSTOMER_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_ORDER_TYPE" ADD CONSTRAINT "T_ORDER_TYPE_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_ORDER" ADD CONSTRAINT "T_ORDER_PK" PRIMARY KEY ("ID");
ALTER TABLE "WEBSTORE"."T_ORDER_DETAILS" ADD CONSTRAINT "T_ORDER_DETAILS_PK" PRIMARY KEY ("ID");



--------------------------------------------------------
-- 	CREATE TABLE FOREIGN KEYS 
--------------------------------------------------------

ALTER TABLE "WEBSTORE"."T_USER" ADD CONSTRAINT "T_USER_ROLE_FK1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "WEBSTORE"."T_ROLE" ("ID") ENABLE;
	  
ALTER TABLE "WEBSTORE"."T_PRODUCT" ADD CONSTRAINT "T_PRODUCT_PRODUCT_TYPE_FK1" FOREIGN KEY ("PRODUCT_TYPE_ID")
	  REFERENCES "WEBSTORE"."T_PRODUCT_TYPE" ("ID") ENABLE;

ALTER TABLE "WEBSTORE"."T_CUSTOMER" ADD CONSTRAINT "T_CUSTOMER_ROLE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "WEBSTORE"."T_USER" ("ID") ENABLE;


ALTER TABLE "WEBSTORE"."T_ORDER" ADD CONSTRAINT "T_ORDER_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "WEBSTORE"."T_CUSTOMER" ("ID") ENABLE;
ALTER TABLE "WEBSTORE"."T_ORDER" ADD CONSTRAINT "T_ORDER_ORDER_TYPE_FK1" FOREIGN KEY ("ORDER_TYPE_ID")
	  REFERENCES "WEBSTORE"."T_ORDER_TYPE" ("ID") ENABLE;


ALTER TABLE "WEBSTORE"."T_ORDER_DETAILS" ADD CONSTRAINT "T_ORDER_DETAILS_ORDER_FK1" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "WEBSTORE"."T_ORDER" ("ID") ENABLE;
ALTER TABLE "WEBSTORE"."T_ORDER_DETAILS" ADD CONSTRAINT "T_ORDER_DETAILS_PRODUCT__FK1" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "WEBSTORE"."T_PRODUCT" ("ID") ENABLE;

--------------------------------------------------------
-- 	INSERT DATA 
--------------------------------------------------------
INSERT INTO WEBSTORE.T_ROLE (ID, NAME) VALUES  (1, 'ROLE_ADMIN');
INSERT INTO WEBSTORE.T_ROLE (ID, NAME) VALUES  (2, 'ROLE_USER');


INSERT INTO WEBSTORE.T_USER (ID, USERNAME, PASSWORD, ROLE_ID) VALUES  (1, 'admin', '96e79218965eb72c92a549dd5a330112', 1);
INSERT INTO WEBSTORE.T_USER (ID, USERNAME, PASSWORD, ROLE_ID) VALUES  (2, 'user','96e79218965eb72c92a549dd5a330112', 2);

INSERT INTO WEBSTORE.T_PRODUCT_TYPE (ID, NAME) VALUES  (1, 'Computers');
INSERT INTO WEBSTORE.T_PRODUCT_TYPE (ID, NAME) VALUES  (2, 'Electronics');
INSERT INTO WEBSTORE.T_PRODUCT_TYPE (ID, NAME) VALUES  (3, 'TV');

INSERT INTO WEBSTORE.T_PRODUCT (ID, NAME, PRODUCT_TYPE_ID, SINGLE_PRICE, QUANTITY, ACTIVE) VALUES (1, 'Notebook Dell E1505', 1, 1000, 20, 1);
INSERT INTO WEBSTORE.T_PRODUCT (ID, NAME, PRODUCT_TYPE_ID, SINGLE_PRICE, QUANTITY, ACTIVE) VALUES (2, 'Notebook Asus G552VW-CN287D', 1, 2500, 10, 1);
INSERT INTO WEBSTORE.T_PRODUCT (ID, NAME, PRODUCT_TYPE_ID, SINGLE_PRICE, QUANTITY, ACTIVE) VALUES (3, 'Notebook Lenovo Yoga Tab 3 Pro', 1, 2000, 30, 1);

   
--------------------------------------------------------
-- 	SET ORACLE SESSION TO COMPARE INSENSITIVE DATA LIKE 'aAA' == 'AAA' 
--------------------------------------------------------
   
ALTER SESSION SET NLS_COMP=LINGUISTIC;